- name: Deploy Ghost Theme
  # You may pin to the exact commit or the version.
  # uses: TryGhost/action-deploy-theme@26652c5cee097c6b31bbd3319b8427369043a566
  uses: TryGhost/action-deploy-theme@v1.4.1
  with:
    # Ghost Admin API Url
    api-url: 
    # Ghost Admin API Key
    api-key: 
    # Files or folders to exclude (space-separated list)
    exclude: # optional
    # A custom theme name that overrides the default name in package.json
    theme-name: # optional
    # Path to a built zip file. If this is included, the `exclude` and `theme-name` options are ignored
    file: # optional
